In [1]:
import tensorflow as tf
x=tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [2]:
import tensorflow as tf
x=tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [4]:
import tensorflow as tf
x=tf.random.normal(shape=(3,1),mean=0, stddev=1.)
print(x)
y=tf.random.uniform(shape=(3,1), minval=0, maxval=1.)
print(y)

tf.Tensor(
[[-0.08533717]
 [-1.2298262 ]
 [ 0.43154067]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.55037844]
 [0.4219135 ]
 [0.84889257]], shape=(3, 1), dtype=float32)


In [11]:

import tensorflow as tf
v=tf.Variable(initial_value=tf.ones(shape=(3,2)))
print(v)
v.assign(tf.zeros(shape=(3,2)))
print(v)
v[0,0].assign(4.)
print(v)
v.assign_add(tf.ones((3,2)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[4., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[5., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>


In [13]:
#import tensorflow as tf
kk=tf.Variable(initial_value=4.)
print(kk)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>


In [15]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d

tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
